// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Database;

namespace Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200804020121_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Amount = 112m,
                            ContractType = "Monthly",
                            Name = "Employee 1",
                            Surname = "Surname Employee 1"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Amount = 818m,
                            ContractType = "Hourly",
                            Name = "Employee 2",
                            Surname = "Surname Employee 2"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Amount = 981m,
                            ContractType = "Monthly",
                            Name = "Employee 3",
                            Surname = "Surname Employee 3"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Amount = 481m,
                            ContractType = "Monthly",
                            Name = "Employee 4",
                            Surname = "Surname Employee 4"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Amount = 518m,
                            ContractType = "Monthly",
                            Name = "Employee 5",
                            Surname = "Surname Employee 5"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Amount = 201m,
                            ContractType = "Monthly",
                            Name = "Employee 6",
                            Surname = "Surname Employee 6"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Amount = 948m,
                            ContractType = "Monthly",
                            Name = "Employee 7",
                            Surname = "Surname Employee 7"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Amount = 439m,
                            ContractType = "Hourly",
                            Name = "Employee 8",
                            Surname = "Surname Employee 8"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Amount = 140m,
                            ContractType = "Hourly",
                            Name = "Employee 9",
                            Surname = "Surname Employee 9"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Amount = 164m,
                            ContractType = "Hourly",
                            Name = "Employee 10",
                            Surname = "Surname Employee 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
